function [covarEst,uEst] = pred_step(uPrev,covarPrev,angVel,acc,dt)
%covarPrev and uPrev are the previous mean and covariance respectively
%angVel is the angular velocity
%acc is the acceleration
%dt is the sampling time
syms p q p_dot bg ba
X = [p; q; p_dot; bg; ba];
p = [uPrev(1); uPrev(2); uPrev(3)];
q = [uPrev(4); uPrev(5); uPrev(6)];
p_dot = [uPrev(7); uPrev(8); uPrev(9)];
bg = [uPrev(10); uPrev(11); uPrev(12)];
ba = [uPrev(13); uPrev(14); uPrev(15)];

w_m = [angVel(1); angVel(2); angVel(3)];
a_m = [acc(1); acc(2); acc(3)];

ng = [0;0;0]; 
na = [0;0;0];
nbg = [0;0;0];
nba = [0;0;0];

g = [0;  0; -9.81];

eul = [q(3) q(2) q(1)];
R = eul2rotm(eul, 'ZYX'); 

G = [0 -sin(q(3)) cos(q(3))*cos(q(2));
     0  cos(q(3)) sin(q(3))*cos(q(2));
     1 0 -sin(q(2))];

f_xun = [p_dot; inv(G)*(w_m - bg - ng); g + R*(a_m - ba - na); nbg; nba];

A_t = [0, 0, 0,                                                                                                                                         0,                                                                                                                                                                                                                                                                                                                                                                                                                                           0,                                                                                                                                                                             0, 1, 0, 0,                                                                0,                                                                0,  0,                  0,                                                0,                                                0;
    0, 0, 0,                                                                                                                                         0,                                                                                                                                                                                                                                                                                                                                                                                                                                           0,                                                                                                                                                                             0, 0, 1, 0,                                                                0,                                                                0,  0,                  0,                                                0,                                                0;
    0, 0, 0,                                                                                                                                         0,                                                                                                                                                                                                                                                                                                                                                                                                                                           0,                                                                                                                                                                             0, 0, 0, 1,                                                                0,                                                                0,  0,                  0,                                                0,                                                0;
    0, 0, 0,                                                                                                                                         0, - (cos(q(2))*cos(q(3))*(bg(1) + 0 - w_m(1)))/(cos(q(2))*cos(q(3))^2 + cos(q(2))*sin(q(3))^2) - (cos(q(2))*sin(q(3))*(bg(2) + 0 - w_m(2)))/(cos(q(2))*cos(q(3))^2 + cos(q(2))*sin(q(3))^2) - (cos(q(3))*sin(q(2))*(sin(q(2))*cos(q(3))^2 + sin(q(2))*sin(q(3))^2)*(bg(1) + 0 - w_m(1)))/(cos(q(2))*cos(q(3))^2 + cos(q(2))*sin(q(3))^2)^2 - (sin(q(2))*sin(q(3))*(sin(q(2))*cos(q(3))^2 + sin(q(2))*sin(q(3))^2)*(bg(2) + 0 - w_m(2)))/(cos(q(2))*cos(q(3))^2 + cos(q(2))*sin(q(3))^2)^2,         (sin(q(2))*sin(q(3))*(bg(1) + 0 - w_m(1)))/(cos(q(2))*cos(q(3))^2 + cos(q(2))*sin(q(3))^2) - (cos(q(3))*sin(q(2))*(bg(2) + 0 - w_m(2)))/(cos(q(2))*cos(q(3))^2 + cos(q(2))*sin(q(3))^2), 0, 0, 0, -(cos(q(3))*sin(q(2)))/(cos(q(2))*cos(q(3))^2 + cos(q(2))*sin(q(3))^2), -(sin(q(2))*sin(q(3)))/(cos(q(2))*cos(q(3))^2 + cos(q(2))*sin(q(3))^2), -1,     0,                                                0,                                                0;
    0, 0, 0,                                                                                                                                         0,                                                                                                                                                                                                                                                                                                                                                                                                                                           0,                                                               (cos(q(3))*(bg(1) + 0 - w_m(1)))/(cos(q(3))^2 + sin(q(3))^2) + (sin(q(3))*(bg(2) + 0 - w_m(2)))/(cos(q(3))^2 + sin(q(3))^2), 0, 0, 0,                               sin(q(3))/(cos(q(3))^2 + sin(q(3))^2),                              -cos(q(3))/(cos(q(3))^2 + sin(q(3))^2),  0,                  0,                                                0,                                                0;
    0, 0, 0,                                                                                                                                         0,                                                                                                                                                                                           - (cos(q(3))*(sin(q(2))*cos(q(3))^2 + sin(q(2))*sin(q(3))^2)*(bg(1) + 0 - w_m(1)))/(cos(q(2))*cos(q(3))^2 + cos(q(2))*sin(q(3))^2)^2 - (sin(q(3))*(sin(q(2))*cos(q(3))^2 + sin(q(2))*sin(q(3))^2)*(bg(2) + 0 - w_m(2)))/(cos(q(2))*cos(q(3))^2 + cos(q(2))*sin(q(3))^2)^2,                           (sin(q(3))*(bg(1) + 0 - w_m(1)))/(cos(q(2))*cos(q(3))^2 + cos(q(2))*sin(q(3))^2) - (cos(q(3))*(bg(2) + 0 - w_m(2)))/(cos(q(2))*cos(q(3))^2 + cos(q(2))*sin(q(3))^2), 0, 0, 0,            -cos(q(3))/(cos(q(2))*cos(q(3))^2 + cos(q(2))*sin(q(3))^2),            -sin(q(3))/(cos(q(2))*cos(q(3))^2 + cos(q(2))*sin(q(3))^2),  0,                  0,                                                0,                                                0;
    0, 0, 0, - (sin(q(1))*sin(q(3)) + cos(q(1))*cos(q(3))*sin(q(2)))*(ba(2) - a_m(2) + 0) - (cos(q(1))*sin(q(3)) - cos(q(3))*sin(q(1))*sin(q(2)))*(ba(3) - a_m(3) + 0),                                                                                                                                                                                                                                                                                                           cos(q(3))*sin(q(2))*(ba(1) - a_m(1) + 0) - cos(q(1))*cos(q(2))*cos(q(3))*(ba(3) - a_m(3) + 0) - cos(q(2))*cos(q(3))*sin(q(1))*(ba(2) - a_m(2) + 0), (cos(q(1))*cos(q(3)) + sin(q(1))*sin(q(2))*sin(q(3)))*(ba(2) - a_m(2) + 0) - (cos(q(3))*sin(q(1)) - cos(q(1))*sin(q(2))*sin(q(3)))*(ba(3) - a_m(3) + 0) + cos(q(2))*sin(q(3))*(ba(1) - a_m(1) + 0), 0, 0, 0,                                                                0,                                                                0,  0, -cos(q(2))*cos(q(3)),   cos(q(1))*sin(q(3)) - cos(q(3))*sin(q(1))*sin(q(2)), - sin(q(1))*sin(q(3)) - cos(q(1))*cos(q(3))*sin(q(2));
    0, 0, 0,   (cos(q(3))*sin(q(1)) - cos(q(1))*sin(q(2))*sin(q(3)))*(ba(2) - a_m(2) + 0) + (cos(q(1))*cos(q(3)) + sin(q(1))*sin(q(2))*sin(q(3)))*(ba(3) - a_m(3) + 0),                                                                                                                                                                                                                                                                                                           sin(q(2))*sin(q(3))*(ba(1) - a_m(1) + 0) - cos(q(1))*cos(q(2))*sin(q(3))*(ba(3) - a_m(3) + 0) - cos(q(2))*sin(q(1))*sin(q(3))*(ba(2) - a_m(2) + 0), (cos(q(1))*sin(q(3)) - cos(q(3))*sin(q(1))*sin(q(2)))*(ba(2) - a_m(2) + 0) - (sin(q(1))*sin(q(3)) + cos(q(1))*cos(q(3))*sin(q(2)))*(ba(3) - a_m(3) + 0) - cos(q(2))*cos(q(3))*(ba(1) - a_m(1) + 0), 0, 0, 0,                                                                0,                                                                0,  0, -cos(q(2))*sin(q(3)), - cos(q(1))*cos(q(3)) - sin(q(1))*sin(q(2))*sin(q(3)),   cos(q(3))*sin(q(1)) - cos(q(1))*sin(q(2))*sin(q(3));
    0, 0, 0,                                                                 cos(q(2))*sin(q(1))*(ba(3) - a_m(3) + 0) - cos(q(1))*cos(q(2))*(ba(2) - a_m(2) + 0),                                                                                                                                                                                                                                                                                                                                      cos(q(2))*(ba(1) - a_m(1) + 0) + cos(q(1))*sin(q(2))*(ba(3) - a_m(3) + 0) + sin(q(1))*sin(q(2))*(ba(2) - a_m(2) + 0),                                                                                                                                                                             0, 0, 0, 0,                                                                0,                                                                0,  0,           sin(q(2)),                               -cos(q(2))*sin(q(1)),                               -cos(q(1))*cos(q(2));
    0, 0, 0,                                                                                                                                         0,                                                                                                                                                                                                                                                                                                                                                                                                                                           0,                                                                                                                                                                             0, 0, 0, 0,                                                                0,                                                                0,  0,                  0,                                                0,                                                0;
    0, 0, 0,                                                                                                                                         0,                                                                                                                                                                                                                                                                                                                                                                                                                                           0,                                                                                                                                                                             0, 0, 0, 0,                                                                0,                                                                0,  0,                  0,                                                0,                                                0;
    0, 0, 0,                                                                                                                                         0,                                                                                                                                                                                                                                                                                                                                                                                                                                           0,                                                                                                                                                                             0, 0, 0, 0,                                                                0,                                                                0,  0,                  0,                                                0,                                                0;
    0, 0, 0,                                                                                                                                         0,                                                                                                                                                                                                                                                                                                                                                                                                                                           0,                                                                                                                                                                             0, 0, 0, 0,                                                                0,                                                                0,  0,                  0,                                                0,                                                0;
    0, 0, 0,                                                                                                                                         0,                                                                                                                                                                                                                                                                                                                                                                                                                                           0,                                                                                                                                                                             0, 0, 0, 0,                                                                0,                                                                0,  0,                  0,                                                0,                                                0;
    0, 0, 0,                                                                                                                                         0,                                                                                                                                                                                                                                                                                                                                                                                                                                           0,                                                                                                                                                                             0, 0, 0, 0,                                                                0,                                                                0,  0,                  0,                                                0,                                                0];
%A_t is the Jacobian calculated of function f_xun wrt the state space

U_t = [                                                               0,                                                                0,  0,                  0,                                                0,                                                0, 0, 0, 0, 0, 0, 0;
                                                               0,                                                                0,  0,                  0,                                                0,                                                0, 0, 0, 0, 0, 0, 0;
                                                              0,                                                                0,  0,                  0,                                                0,                                                0, 0, 0, 0, 0, 0, 0;
 -(cos(q(3))*sin(q(2)))/(cos(q(2))*cos(q(3))^2 + cos(q(2))*sin(q(3))^2), -(sin(q(2))*sin(q(3)))/(cos(q(2))*cos(q(3))^2 + cos(q(2))*sin(q(3))^2), -1,                  0,                                                0,                                                0, 0, 0, 0, 0, 0, 0;
                               sin(q(3))/(cos(q(3))^2 + sin(q(3))^2),                              -cos(q(3))/(cos(q(3))^2 + sin(q(3))^2),  0,                  0,                                                0,                                                0, 0, 0, 0, 0, 0, 0;
            -cos(q(3))/(cos(q(2))*cos(q(3))^2 + cos(q(2))*sin(q(3))^2),            -sin(q(3))/(cos(q(2))*cos(q(3))^2 + cos(q(2))*sin(q(3))^2),  0,                  0,                                                0,                                                0, 0, 0, 0, 0, 0, 0;
                                                                0,                                                                0,  0, -cos(q(2))*cos(q(3)),   cos(q(1))*sin(q(3)) - cos(q(3))*sin(q(1))*sin(q(2)), - sin(q(1))*sin(q(3)) - cos(q(1))*cos(q(3))*sin(q(2)), 0, 0, 0, 0, 0, 0;
                                                                0,                                                                0,  0, -cos(q(2))*sin(q(3)), - cos(q(1))*cos(q(3)) - sin(q(1))*sin(q(2))*sin(q(3)),   cos(q(3))*sin(q(1)) - cos(q(1))*sin(q(2))*sin(q(3)), 0, 0, 0, 0, 0, 0;
                                                                0,                                                                0,  0,           sin(q(2)),                               -cos(q(2))*sin(q(1)),                               -cos(q(1))*cos(q(2)), 0, 0, 0, 0, 0, 0;
                                                                0,                                                                0,  0,                  0,                                                0,                                                0, 1, 0, 0, 0, 0, 0;
                                                                0,                                                                0,  0,                  0,                                                0,                                                0, 0, 1, 0, 0, 0, 0;
                                                                0,                                                                0,  0,                  0,                                                0,                                                0, 0, 0, 1, 0, 0, 0;
                                                                0,                                                                0,  0,                  0,                                                0,                                                0, 0, 0, 0, 1, 0, 0;
                                                                0,                                                                0,  0,                  0,                                                0,                                                0, 0, 0, 0, 0, 1, 0;
                                                                0,                                                                0,  0,                  0,                                                0,                                                0, 0, 0, 0, 0, 0, 1];

% U_t is a jacobian calculated for function f_xun wrt noise ng and na

F_t = eye(15) + dt*A_t;

Q = 0.001*eye(12);

Q_d = dt*Q;

uEst = double(uPrev + dt*f_xun);
covarEst = double(F_t*covarPrev*F_t'+ U_t*Q_d*U_t');

 end